[package]
name = "md-wiki"
version = "0.2.0"
edition = "2024"
description = "Markdown based static site generator for minimal wikis"
repository = "https://github.com/sidju/md-wiki"
readme = "README.md"
categories = []
keywords = ["markdown", "md", "static-site", "wiki"]
authors = ["sidju <contact@sidju.se>"]
license = "MIT"

include = [
  "Cargo.toml",
  "Cargo.lock",
  "src/**/*",
  "LICENSE"
]

[dependencies]
pulldown-cmark = "0.11"
walkdir = "2.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
globset = "0.4"
